<?php if ($block->shouldShowPopup()) {?>
    <div id="modal-overlay" style="display:none;">
        <?php echo $block->getSpecialOfferBlockContent() ?>
    </div>
    <script type="text/x-magento-init">
       {
            "*": {
                "Edvardas_Special/js/special-offer":
                    {
                        "displayTimeout": "<?php echo $block->getPopupTimeoutMilliseconds() ?>"
                    }
            }
       }
    </script>
<?php } ?>